[build]
    base = ""
    publish = "dist/"
    command = "npm run build"
    environment = { NODE_VERSION = "14.15.3" }

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[headers]]
    for = "/*"

    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
